apiVersion: v1
baseDomain: aws.cloudnativedemos.com
controlPlane:   
  hyperthreading: Enabled 
  name: master
  platform:
    aws:
      type: m4.xlarge
  replicas: 3
compute: 
- hyperthreading: Enabled 
  name: worker
  platform:
    aws:
      type: m4.large
  replicas: 2
metadata:
  name: openshift
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: us-east-1
pullSecret: '{}'
fips: false
sshKey: ''
