apiVersion: v1
baseDomain: azure.cloudnativedemos.com 
controlPlane: 
  hyperthreading: Enabled
  name: master
  platform:
    azure:
      type: Standard_D8s_v3
      osDisk:
        diskSizeGB: 128 
  replicas: 3
compute: 
- hyperthreading: Enabled 
  name: worker
  platform:
    azure:
      type: Standard_D2s_v3
      osDisk:
        diskSizeGB: 128
  replicas: 2
metadata:
  name: openshift
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  azure:
    region: southeastasia
    baseDomainResourceGroupName: OCPRG
pullSecret: '{}'
fips: false 
sshKey: '' 
